import * as fs from 'fs'
import * as path from 'path'

const iconsDir: string = path.resolve(__dirname, 'assets')
const outputFilePath: string = path.resolve(__dirname, 'src', 'data', 'symbols.ts')

function parseSVG(content: string): string {
  const pathMatches = [...content.matchAll(/<path[^>]*\sd="([^"]+)"/g)]
  const paths = pathMatches.map(match => match[1]!)

  return paths.join(',')
}

const svgFiles: string[] = fs
  .readdirSync(iconsDir)
  .filter((file: string) => file.endsWith('.svg'))

const icons: Record<string, string> = {}

svgFiles.forEach((file: string) => {
  const filePath: string = path.join(iconsDir, file)
  const iconName: string = path.basename(file, '.svg')
  const svgContent: string = fs.readFileSync(filePath, 'utf8')
  const paths = parseSVG(svgContent)
  icons[iconName] = paths
})

const outputContent: string =
  `// This file was generated by build-symbols.ts\n\n` +
  `export const SYMBOLS = ${JSON.stringify(icons, null, 2)} as const\n`

fs.writeFileSync(outputFilePath, outputContent)