import * as fs from 'fs'
import * as path from 'path'

const svgDir: string = path.resolve(__dirname, 'assets')
const outputFilePath: string = path.resolve(__dirname, 'data', 'symbols.ts')

const svgFiles: string[] = fs.readdirSync(svgDir).filter((file: string) => file.endsWith('.svg'))

const svgData: Record<string, string> = {}

svgFiles.forEach((file: string) => {
  const filePath: string = path.join(svgDir, file)
  const symbolName: string = path.basename(file, '.svg')
  const svgContent: string = fs.readFileSync(filePath, 'utf8')
  const base64Content: string = Buffer.from(svgContent).toString('base64')
  svgData[symbolName] = base64Content
});

const outputContent: string = `// This file was autogenerated by build-symbols.ts\n\nexport const SYMBOLS = ${JSON.stringify(svgData, null, 2)}`

fs.writeFileSync(outputFilePath, outputContent)
